"use client";

import Link from "next/link";
import { useState } from "react";
import { AlertTriangle, ArrowRight, Check, Clock3, Sparkles } from "lucide-react";
import { useRole } from "@/components/role-context";
import { useTasks } from "@/components/task-context";

export function DashboardTasks(){
  const {role}=useRole();const {tasks,createTask}=useTasks();const [created,setCreated]=useState(false);
  const mine=tasks.filter(task=>task.responsible===role).slice(0,3);const overdue=tasks.filter(task=>task.status==="Просрочена").slice(0,2);
  function createFromAi(){createTask({title:"Отработать новый AI-сигнал по посещаемости",type:"AI",responsible:role,related:"Студент · группа ИС-23-1",priority:"Высокий",description:"Проверить причины резкого снижения посещаемости и зафиксировать результат."});setCreated(true);window.setTimeout(()=>setCreated(false),2200)}
  return <section className="mx-auto mb-5 grid max-w-[1600px] gap-4 xl:grid-cols-3"><article className="rounded-2xl border border-slate-100 bg-white p-4 shadow-card"><div className="flex items-center justify-between"><div><h2 className="text-xs font-extrabold">Мои задачи</h2><p className="mt-1 text-[9px] text-slate-400">Поручения для роли «{role}»</p></div><Link href="/tasks" className="text-[9px] font-bold text-primary">Все задачи</Link></div><div className="mt-3 space-y-2">{mine.length?mine.map(task=><Link href="/tasks" key={task.id} className="flex items-center gap-2 rounded-xl bg-slate-50 p-2.5"><span className="grid h-7 w-7 place-items-center rounded-lg bg-white text-primary"><Clock3 size={13}/></span><span className="min-w-0 flex-1 truncate text-[9px] font-bold text-slate-600">{task.title}</span><ArrowRight size={12} className="text-slate-300"/></Link>):<p className="rounded-xl bg-slate-50 p-3 text-[9px] text-slate-400">Нет личных задач</p>}</div></article><article className="rounded-2xl border border-red-100 bg-white p-4 shadow-card"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-xl bg-red-50 text-red-600"><AlertTriangle size={15}/></span><div><h2 className="text-xs font-extrabold">Просроченные поручения</h2><p className="mt-0.5 text-[9px] text-slate-400">Требуют немедленного внимания</p></div><b className="ml-auto text-lg text-red-600">{tasks.filter(task=>task.status==="Просрочена").length}</b></div><div className="mt-3 space-y-2">{overdue.map(task=><Link href="/tasks" key={task.id} className="block rounded-xl bg-red-50/60 p-2.5"><p className="truncate text-[9px] font-bold text-slate-700">{task.title}</p><p className="mt-1 text-[8px] text-red-500">Срок: {task.deadline}</p></Link>)}</div></article><article className="rounded-2xl border border-violet-100 bg-violet-50/40 p-4 shadow-card"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-xl bg-violet-100 text-violet-700"><Sparkles size={15}/></span><div><h2 className="text-xs font-extrabold">AI-рекомендация</h2><p className="mt-0.5 text-[9px] text-slate-400">Обнаружен новый риск-сигнал</p></div></div><p className="mt-3 text-[10px] leading-4 text-slate-600">У студента группы ИС-23-1 посещаемость снизилась на 18% за две недели.</p><button onClick={createFromAi} className={`mt-3 flex h-8 items-center gap-2 rounded-lg px-3 text-[9px] font-bold text-white ${created?"bg-emerald-600":"bg-violet-600"}`}>{created?<><Check size={13}/>Задача создана</>:<><Sparkles size={13}/>Создать задачу</>}</button></article></section>
}
