"use client";

import { useState } from "react";
import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ArrowDownRight, ArrowRight, ArrowUpRight, CalendarDays, CheckCircle2, ChevronRight, Clock3, GraduationCap, MoreHorizontal, UserCheck, Users } from "lucide-react";
import { useRole } from "@/components/role-context";
import { DirectorFocus, RoleDashboard } from "@/components/role-dashboard";

const attendance = [
  { day: "Пн", value: 91 }, { day: "Вт", value: 94 }, { day: "Ср", value: 92 },
  { day: "Чт", value: 96 }, { day: "Пт", value: 93 }, { day: "Сб", value: 88 },
];
const donut = [{ name: "Успевают", value: 72, color: "#2563EB" }, { name: "Требуют внимания", value: 18, color: "#F59E0B" }, { name: "Риск отчисления", value: 10, color: "#E2E8F0" }];
const periods = ["Неделя", "Месяц", "Семестр"];

const stats = [
  { title: "Всего студентов", value: "1 284", delta: "+3,2%", good: true, hint: "с начала семестра", icon: GraduationCap, color: "bg-blue-50 text-primary" },
  { title: "Преподавателей", value: "86", delta: "+2", good: true, hint: "новых сотрудника", icon: Users, color: "bg-violet-50 text-violet-600" },
  { title: "Посещаемость", value: "93,4%", delta: "+1,8%", good: true, hint: "к прошлому месяцу", icon: UserCheck, color: "bg-emerald-50 text-emerald-600" },
  { title: "Средний балл", value: "4,21", delta: "−0,06", good: false, hint: "к прошлому семестру", icon: CheckCircle2, color: "bg-amber-50 text-amber-600" },
];

export function Dashboard() {
  const { role } = useRole();
  const [period, setPeriod] = useState("Неделя");
  if (role !== "Директор") return <RoleDashboard />;
  return <div className="mx-auto max-w-[1500px] animate-rise">
    <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="text-2xl font-extrabold tracking-[-.025em] sm:text-[28px]">Доброе утро, Айгуль!</h1><p className="mt-1.5 text-sm text-slate-500">Вот что происходит в вашем колледже сегодня.</p></div><button className="flex h-10 items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-xs font-bold text-slate-600 shadow-sm hover:bg-slate-50"><CalendarDays size={16} />22 июня 2026<ChevronRight size={14} /></button></div>

    <DirectorFocus />
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map((item, index) => <article key={item.title} style={{ animationDelay: `${index * 70}ms` }} className="animate-rise rounded-2xl border border-slate-100 bg-white p-5 shadow-card"><div className="flex items-start justify-between"><span className={`grid h-11 w-11 place-items-center rounded-xl ${item.color}`}><item.icon size={21} /></span><button className="text-slate-300 hover:text-slate-600"><MoreHorizontal size={19} /></button></div><p className="mt-5 text-xs font-semibold text-slate-400">{item.title}</p><div className="mt-2 flex items-end justify-between gap-2"><p className="text-2xl font-extrabold tracking-tight">{item.value}</p><span className={`flex items-center text-[11px] font-bold ${item.good ? "text-emerald-600" : "text-red-500"}`}>{item.good ? <ArrowUpRight size={14} /> : <ArrowDownRight size={14} />}{item.delta}</span></div><p className="mt-1 text-[10px] text-slate-400">{item.hint}</p></article>)}</section>

    <section className="mt-5 grid gap-5 xl:grid-cols-[1.55fr_.85fr]">
      <article className="rounded-2xl border border-slate-100 bg-white p-5 shadow-card sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 className="text-sm font-extrabold">Динамика посещаемости</h2><p className="mt-1 text-xs text-slate-400">Средний показатель по всем отделениям</p></div><div className="flex w-fit rounded-lg bg-slate-50 p-1">{periods.map((item) => <button key={item} onClick={() => setPeriod(item)} className={`rounded-md px-3 py-1.5 text-[10px] font-bold transition ${period === item ? "bg-white text-primary shadow-sm" : "text-slate-400"}`}>{item}</button>)}</div></div><div className="mt-7 h-[260px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={attendance} margin={{ left: -22, right: 5 }}><defs><linearGradient id="attendanceFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#2563EB" stopOpacity={0.2}/><stop offset="100%" stopColor="#2563EB" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#EEF2F7" vertical={false}/><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{ fill: "#94A3B8", fontSize: 11 }}/><YAxis domain={[80,100]} axisLine={false} tickLine={false} tick={{ fill: "#94A3B8", fontSize: 10 }} tickFormatter={(v) => `${v}%`}/><Tooltip contentStyle={{ borderRadius: 12, border: "none", boxShadow: "0 8px 25px rgba(15,23,42,.12)", fontSize: 12 }} formatter={(value) => [`${value}%`, "Посещаемость"]}/><Area type="monotone" dataKey="value" stroke="#2563EB" strokeWidth={3} fill="url(#attendanceFill)" dot={{ r: 4, fill: "#fff", stroke: "#2563EB", strokeWidth: 2 }}/></AreaChart></ResponsiveContainer></div></article>
      <article className="rounded-2xl border border-slate-100 bg-white p-5 shadow-card sm:p-6"><h2 className="text-sm font-extrabold">Статус успеваемости</h2><p className="mt-1 text-xs text-slate-400">Распределение студентов</p><div className="relative mx-auto mt-4 h-[190px] max-w-[240px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={donut} dataKey="value" innerRadius={62} outerRadius={82} paddingAngle={4} stroke="none">{donut.map((entry) => <Cell key={entry.name} fill={entry.color}/>)}</Pie></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 grid place-content-center text-center"><span className="text-2xl font-extrabold">1 284</span><span className="text-[10px] text-slate-400">студента</span></div></div><div className="space-y-2.5">{donut.map((item) => <div key={item.name} className="flex items-center text-[11px]"><span className="mr-2 h-2 w-2 rounded-full" style={{ backgroundColor: item.color }}/><span className="text-slate-500">{item.name}</span><b className="ml-auto">{item.value}%</b></div>)}</div></article>
    </section>

    <section className="mt-5 grid gap-5 xl:grid-cols-[1.05fr_.95fr]">
      <article className="rounded-2xl border border-slate-100 bg-white p-5 shadow-card sm:p-6"><div className="flex items-center justify-between"><div><h2 className="text-sm font-extrabold">Ближайшие события</h2><p className="mt-1 text-xs text-slate-400">План на эту неделю</p></div><button className="text-xs font-bold text-primary">Все события</button></div><div className="mt-5 space-y-1">{[["24", "ИЮН", "Заседание педагогического совета", "14:30 · Конференц-зал", "bg-blue-50 text-primary"],["25", "ИЮН", "Защита дипломных проектов", "10:00 · Актовый зал", "bg-violet-50 text-violet-600"],["27", "ИЮН", "День открытых дверей", "11:00 · Главный корпус", "bg-emerald-50 text-emerald-600"]].map(([date, month, title, meta, color]) => <button key={title} className="flex w-full items-center gap-3 rounded-xl p-2.5 text-left hover:bg-slate-50"><span className={`grid h-12 w-12 shrink-0 place-content-center rounded-xl text-center ${color}`}><b className="text-base leading-4">{date}</b><small className="text-[8px] font-bold">{month}</small></span><span className="min-w-0"><b className="block truncate text-xs">{title}</b><small className="mt-1 flex items-center gap-1 text-[10px] text-slate-400"><Clock3 size={11}/>{meta}</small></span><ChevronRight size={16} className="ml-auto text-slate-300" /></button>)}</div></article>
      <article className="rounded-2xl border border-slate-100 bg-white p-5 shadow-card sm:p-6"><div className="flex items-center justify-between"><div><h2 className="text-sm font-extrabold">Последние действия</h2><p className="mt-1 text-xs text-slate-400">Изменения в системе</p></div><button className="grid h-8 w-8 place-items-center rounded-lg border border-slate-200"><MoreHorizontal size={16} /></button></div><div className="mt-5 space-y-5">{[["ГК", "Гульмира К.", "добавила приказ №142", "12 мин", "bg-blue-100 text-blue-700"],["АБ", "Аслан Б.", "обновил расписание группы ИС-23-1", "35 мин", "bg-emerald-100 text-emerald-700"],["МС", "Марина С.", "загрузила ведомость за май", "1 ч", "bg-amber-100 text-amber-700"],["Система", "Система", "сформировала отчёт посещаемости", "2 ч", "bg-slate-100 text-slate-600"]].map(([initials, name, action, time, color]) => <div key={`${name}${action}`} className="flex items-center gap-3"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-full text-[10px] font-extrabold ${color}`}>{initials === "Система" ? "ED" : initials}</span><p className="min-w-0 flex-1 truncate text-[11px] text-slate-500"><b className="text-slate-800">{name}</b> {action}</p><span className="text-[10px] text-slate-400">{time}</span></div>)}</div><button className="mt-5 flex items-center gap-1 text-xs font-bold text-primary">Журнал действий <ArrowRight size={14}/></button></article>
    </section>
  </div>;
}
