"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ArrowDownToLine, ArrowUpFromLine, CalendarDays, Camera, Check, Clock3, Eye, FileSpreadsheet, FileText, GraduationCap, MonitorSmartphone, Paperclip, Radio, Search, UserCheck, UserRoundX, Users, Wifi, WifiOff, X } from "lucide-react";
import type { LucideIcon } from "lucide-react";

type DayStatus="Присутствовал"|"Опоздал"|"Отсутствовал"|"Ушёл раньше";
const tabs=["Обзор","Live-лента","По группам","По студентам","Терминалы","Корректировки","Отчёты"];
const liveEvents=[
  ["Алимжан Нурланов","ИС-23-1","Главный вход","09:42:18","Вход","Опоздал","ST-2024-0188"],
  ["Диана Сарсенова","БУ-24-2","Корпус А","09:41:52","Вход","Присутствовал","ST-2025-0211"],
  ["Мансур Касымов","ЭЛ-22-1","Столовая","09:41:07","Вход","Присутствовал","ST-2023-0094"],
  ["Аружан Тлеубаева","ДО-23-2","Библиотека","09:40:31","Вход","Присутствовал","ST-2024-0238"],
  ["Тимур Омаров","ИС-24-1","Корпус Б","09:39:44","Вход","Опоздал","ST-2025-0267"],
  ["Айдана Серикова","ИС-23-1","Главный вход","09:38:20","Выход","Ушёл раньше","ST-2024-0194"],
  ["Арман Толеуов","СТ-23-2","Общежитие","09:37:58","Вход","Присутствовал","ST-2024-0226"],
];
const groups=[
  ["ИС-23-1","Г. Касенова","24","22","2","5","1","91,7%","Высокий"],
  ["БУ-24-2","М. Соколова","28","27","1","2","0","96,4%","Низкий"],
  ["ЭЛ-22-1","А. Беков","22","19","3","4","2","86,4%","Средний"],
  ["ДО-23-2","Ж. Абиева","26","25","1","1","0","96,2%","Низкий"],
  ["СТ-23-2","Е. Нургалиев","25","21","4","6","2","84,0%","Высокий"],
  ["ИС-24-1","Р. Ахметов","27","23","4","8","1","85,2%","Высокий"],
];
const groupStudents=[
  ["Алимжан Нурланов","Опоздал","08:17","16:42","Главный вход","Главный вход","17","Опоздание без причины","ST-2024-0188"],
  ["Айдана Серикова","Ушёл раньше","07:54","14:12","Корпус А","Корпус Б","0","Заявление куратора","ST-2024-0194"],
  ["Нурали Касымов","Присутствовал","07:48","16:31","Главный вход","Библиотека","0","—","ST-2024-0201"],
  ["Мария Ким","Отсутствовал","—","—","—","—","0","Медицинская справка","ST-2024-0208"],
  ["Сабина Ахметова","Присутствовал","07:52","16:28","Общежитие","Главный вход","0","—","ST-2024-0214"],
  ["Арман Алиев","Опоздал","08:09","16:20","Корпус А","Корпус А","9","Транспортная задержка","ST-2024-0220"],
];
const students=[
  ["Алимжан Нурланов","ИС-23-1","Опоздал","08:17","Главный вход","16:42","Главный вход","78%","9","7","ST-2024-0188"],
  ["Диана Сарсенова","БУ-24-2","Присутствовал","07:51","Корпус А","16:08","Корпус А","96%","1","0","ST-2025-0211"],
  ["Мансур Касымов","ЭЛ-22-1","Присутствовал","07:58","Корпус Б","16:24","Корпус Б","86%","4","3","ST-2023-0094"],
  ["Аружан Тлеубаева","ДО-23-2","Отсутствовал","—","—","—","—","82%","3","5","ST-2024-0238"],
  ["Тимур Омаров","ИС-24-1","Опоздал","08:26","Главный вход","15:55","Корпус Б","69%","12","8","ST-2025-0267"],
  ["Айдана Серикова","ИС-23-1","Ушёл раньше","07:54","Корпус А","14:12","Корпус Б","84%","2","2","ST-2024-0194"],
];
const terminals=[
  ["Главный вход","Онлайн","09:42:18 · Алимжан Н.","684","Главный корпус","Основная проходная"],
  ["Корпус А","Онлайн","09:41:52 · Диана С.","412","Учебный корпус А","Студенты и сотрудники"],
  ["Корпус Б","Онлайн","09:39:44 · Тимур О.","386","Учебный корпус Б","Лабораторный блок"],
  ["Общежитие","Онлайн","09:37:58 · Арман Т.","218","Общежитие №1","Проживающие студенты"],
  ["Столовая","Онлайн","09:41:07 · Мансур К.","526","Главный корпус","Зона питания"],
  ["Библиотека","Офлайн","Вчера, 18:41","0","Главный корпус","Читальный зал"],
];
const corrections=[
  ["КР-2026-0081","Алимжан Нурланов","17.06.2026","Отсутствовал → присутствовал","Г. Касенова","Медицинская справка","spravka-075.pdf","Подтверждено"],
  ["КР-2026-0079","Мария Ким","16.06.2026","Добавлено время выхода","А. Беков","Сбой терминала","акт-сбоя.pdf","На проверке"],
  ["КР-2026-0076","Тимур Омаров","12.06.2026","Опоздание отменено","Г. Касенова","Служебная поездка","приказ-44.pdf","Подтверждено"],
  ["КР-2026-0071","Диана Сарсенова","10.06.2026","Добавлено посещение","М. Соколова","Терминал офлайн","—","Ожидает документ"],
];
const eventTrend=[{time:"08:00",events:421},{time:"09:00",events:982},{time:"10:00",events:1284},{time:"11:00",events:1640},{time:"12:00",events:2108},{time:"13:00",events:2386},{time:"14:00",events:2791},{time:"15:00",events:3124},{time:"16:00",events:3648}];
const statusStyle:Record<DayStatus,string>={"Присутствовал":"bg-emerald-50 text-emerald-700","Опоздал":"bg-amber-50 text-amber-700","Отсутствовал":"bg-red-50 text-red-700","Ушёл раньше":"bg-orange-50 text-orange-700"};
const overviewStats: [string, string, LucideIcon, string][] = [
  ["Пришли сегодня", "1 128", UserCheck, "bg-emerald-50 text-emerald-600"],
  ["Отсутствуют", "96", UserRoundX, "bg-red-50 text-red-600"],
  ["Опоздали", "42", Clock3, "bg-amber-50 text-amber-600"],
  ["Ушли раньше", "18", ArrowUpFromLine, "bg-orange-50 text-orange-600"],
  ["Среднее время входа", "08:04", ArrowDownToLine, "bg-blue-50 text-primary"],
  ["Активные терминалы", "5 / 6", Wifi, "bg-cyan-50 text-cyan-600"],
  ["Событий сегодня", "3 648", Radio, "bg-violet-50 text-violet-600"],
];
const reportDefinitions: [string, string, LucideIcon][] = [
  ["Отчёт по группе", "Посещаемость, опоздания и пропуски выбранной группы", Users],
  ["Отчёт по студенту", "Персональная история Face ID за период", GraduationCap],
  ["Отчёт за период", "Общий отчёт колледжа по датам", CalendarDays],
  ["Отчёт по терминалам", "События и доступность оборудования", MonitorSmartphone],
];

function GroupModal({group,onClose}:{group:string[];onClose:()=>void}){return <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-slate-900/35 p-4 backdrop-blur-[2px]" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><div className="my-4 w-full max-w-6xl animate-rise rounded-[22px] bg-white shadow-2xl"><div className="flex items-start justify-between border-b border-slate-100 px-6 py-5"><div><h2 className="text-lg font-extrabold">Посещаемость группы {group[0]}</h2><p className="mt-1 text-xs text-slate-400">Куратор: {group[1]} · сегодня пришли {group[3]} из {group[2]}</p></div><button onClick={onClose} className="grid h-9 w-9 place-items-center rounded-xl bg-slate-50 text-slate-400"><X size={18}/></button></div><div className="max-h-[72vh] overflow-x-auto"><table className="w-full min-w-[1250px]"><thead><tr className="bg-slate-50/80">{["Студент","Статус дня","Вход","Выход","Терминал входа","Терминал выхода","Опоздание","Комментарий","Действия"].map(column=><th key={column} className="px-4 py-3 text-left text-[9px] font-extrabold uppercase tracking-wider text-slate-400">{column}</th>)}</tr></thead><tbody>{groupStudents.map(row=><tr key={row[0]} className="border-t border-slate-100"><td className="px-4 py-4 text-[10px] font-bold">{row[0]}</td><td className="px-4 py-4"><span className={`rounded-full px-2.5 py-1 text-[9px] font-bold ${statusStyle[row[1] as DayStatus]}`}>{row[1]}</span></td>{row.slice(2,8).map((cell,index)=><td key={`${cell}-${index}`} className="px-4 py-4 text-[10px] text-slate-500">{index===4?`${cell} мин`:cell}</td>)}<td className="px-4"><Link href={`/students/${row[8]}`} className="whitespace-nowrap rounded-lg bg-primary px-3 py-2 text-[9px] font-bold text-white">Открыть личное дело</Link></td></tr>)}</tbody></table></div></div></div>}

function DetailModal({event,onClose}:{event:string[];onClose:()=>void}){return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-900/35 p-4 backdrop-blur-[2px]" onMouseDown={target=>{if(target.target===target.currentTarget)onClose()}}><div className="w-full max-w-md animate-rise rounded-[22px] bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><span className="grid h-12 w-12 place-items-center rounded-xl bg-blue-50 text-sm font-extrabold text-primary">{event[0].split(" ").map(value=>value[0]).join("")}</span><h2 className="mt-4 text-lg font-extrabold">Детали Face ID события</h2></div><button onClick={onClose}><X size={18}/></button></div><dl className="mt-5 space-y-3 rounded-xl bg-slate-50 p-4 text-[10px]">{[["Студент",event[0]],["Группа",event[1]],["Терминал",event[2]],["Время",event[3]],["Тип события",event[4]],["Статус",event[5]],["Источник","Face ID · совпадение 98,7%"]].map(([label,value])=><div key={label} className="flex justify-between gap-3"><dt className="text-slate-400">{label}</dt><dd className="text-right font-bold">{value}</dd></div>)}</dl><Link href={`/students/${event[6]}`} className="mt-5 flex h-10 items-center justify-center rounded-xl bg-primary text-[10px] font-bold text-white">Открыть личное дело</Link></div></div>}

function CorrectionModal({onClose,onSave}:{onClose:()=>void;onSave:()=>void}){return <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-slate-900/35 p-4 backdrop-blur-[2px]"><form onSubmit={event=>{event.preventDefault();onSave()}} className="my-4 w-full max-w-xl animate-rise rounded-[22px] bg-white shadow-2xl"><div className="flex items-start justify-between border-b border-slate-100 px-6 py-5"><div><h2 className="text-lg font-extrabold">Ручная корректировка посещения</h2><p className="mt-1 text-xs text-slate-400">Изменение будет сохранено только в демо-сессии</p></div><button type="button" onClick={onClose}><X size={18}/></button></div><div className="grid gap-4 p-6 sm:grid-cols-2"><label className="text-[11px] font-bold text-slate-600 sm:col-span-2">Студент<input required defaultValue="Алимжан Нурланов" className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-xs"/></label><label className="text-[11px] font-bold text-slate-600">Дата<input type="date" className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-xs"/></label><label className="text-[11px] font-bold text-slate-600">Статус<select className="mt-2 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-xs"><option>Присутствовал</option><option>Опоздал</option><option>Отсутствовал</option><option>Ушёл раньше</option></select></label><label className="text-[11px] font-bold text-slate-600">Время входа<input type="time" className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-xs"/></label><label className="text-[11px] font-bold text-slate-600">Время выхода<input type="time" className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-xs"/></label><label className="text-[11px] font-bold text-slate-600 sm:col-span-2">Причина<textarea className="mt-2 min-h-20 w-full rounded-xl border border-slate-200 p-3 text-xs"/></label><label className="text-[11px] font-bold text-slate-600 sm:col-span-2">Подтверждающий документ<label className="mt-2 flex h-16 items-center justify-center gap-2 rounded-xl border border-dashed border-slate-300 text-[10px] text-slate-400"><Paperclip size={15}/>Прикрепить файл<input type="file" className="hidden"/></label></label></div><div className="flex justify-end gap-2 border-t border-slate-100 px-6 py-4"><button type="button" onClick={onClose} className="h-10 rounded-xl border border-slate-200 px-4 text-xs font-bold">Отмена</button><button className="h-10 rounded-xl bg-primary px-5 text-xs font-bold text-white">Сохранить</button></div></form></div>}

export function FaceIdAttendance(){const [active,setActive]=useState("Обзор");const [group,setGroup]=useState<string[]|null>(null);const [event,setEvent]=useState<string[]|null>(null);const [correction,setCorrection]=useState(false);const [toast,setToast]=useState("");const [query,setQuery]=useState("");function showToast(message:string){setToast(message);window.setTimeout(()=>setToast(""),2400)}const filteredStudents=useMemo(()=>students.filter(student=>student.join(" ").toLowerCase().includes(query.toLowerCase())),[query]);return <div className="mx-auto max-w-[1600px] animate-rise"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-primary text-white shadow-lg shadow-blue-200"><Camera size={23}/></span><div><h1 className="text-2xl font-extrabold tracking-[-.03em] sm:text-[28px]">Посещаемость Face ID</h1><p className="mt-1.5 text-sm text-slate-500">Колледж, корпуса, группы и персональные события студентов</p></div></div><div className="flex gap-2"><span className="flex items-center gap-2 rounded-xl border border-emerald-100 bg-emerald-50 px-3 text-[9px] font-bold text-emerald-700"><Radio size={13} className="animate-pulse"/>Live · 5 терминалов онлайн</span><button onClick={()=>setCorrection(true)} className="h-10 rounded-xl bg-primary px-4 text-[10px] font-bold text-white">Ручная корректировка</button></div></div><div className="mt-6 overflow-x-auto border-b border-slate-200"><div className="flex min-w-max">{tabs.map(tab=><button key={tab} onClick={()=>setActive(tab)} className={`relative px-5 py-3.5 text-[10px] font-bold ${active===tab?"text-primary":"text-slate-400"}`}>{tab}{active===tab?<span className="absolute inset-x-4 bottom-0 h-0.5 bg-primary"/>:null}</button>)}</div></div>
  {active==="Обзор"?<div className="mt-5 space-y-5"><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-7">{overviewStats.map(([label,value,Icon,color])=><article key={label} className="rounded-2xl border border-slate-100 bg-white p-4 shadow-card"><div className="flex items-start justify-between"><span className={`grid h-9 w-9 place-items-center rounded-xl ${color}`}><Icon size={16}/></span><b className="text-lg">{value}</b></div><p className="mt-3 text-[9px] font-bold text-slate-500">{label}</p></article>)}</section><section className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><article className="rounded-2xl border border-slate-100 bg-white p-5 shadow-card"><div className="flex items-center justify-between"><div><h2 className="text-sm font-extrabold">События за сегодня</h2><p className="mt-1 text-[9px] text-slate-400">Накопительная динамика входов и выходов</p></div><b className="text-xl">3 648</b></div><div className="mt-4 h-[260px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={eventTrend}><defs><linearGradient id="faceFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#2563EB" stopOpacity={.22}/><stop offset="1" stopColor="#2563EB" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#EEF2F7"/><XAxis dataKey="time" axisLine={false} tickLine={false} tick={{fontSize:9}}/><YAxis axisLine={false} tickLine={false} tick={{fontSize:9}}/><Tooltip contentStyle={{border:"none",borderRadius:12,fontSize:10}}/><Area dataKey="events" name="События" stroke="#2563EB" strokeWidth={3} fill="url(#faceFill)"/></AreaChart></ResponsiveContainer></div></article><article className="rounded-2xl border border-slate-100 bg-white p-5 shadow-card"><h2 className="text-sm font-extrabold">По корпусам</h2><div className="mt-4 space-y-3">{[["Главный корпус","612 / 684","89,5%"],["Корпус А","248 / 276","89,9%"],["Корпус Б","196 / 224","87,5%"],["Общежитие","72 / 86","83,7%"]].map(([name,count,rate])=><div key={name} className="rounded-xl bg-slate-50 p-3"><div className="flex justify-between text-[9px]"><b>{name}</b><span>{count}</span></div><div className="mt-2 h-2 rounded-full bg-slate-200"><div className="h-full rounded-full bg-primary" style={{width:rate}}/></div><p className="mt-1 text-right text-[8px] text-slate-400">{rate}</p></div>)}</div></article></section></div>:null}
  {active==="Live-лента"?<section className="mt-5 rounded-2xl border border-slate-100 bg-white p-5 shadow-card"><div className="flex items-center justify-between"><div><h2 className="flex items-center gap-2 text-sm font-extrabold"><span className="h-2 w-2 animate-pulse rounded-full bg-red-500"/>Live-лента событий</h2><p className="mt-1 text-[9px] text-slate-400">Обновляется автоматически · последнее событие 3 сек назад</p></div><span className="rounded-lg bg-red-50 px-2 py-1 text-[9px] font-bold text-red-600">LIVE</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{liveEvents.map(item=><article key={`${item[0]}-${item[3]}`} className="rounded-2xl border border-slate-100 p-4 hover:border-blue-200"><div className="flex items-start gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-blue-50 text-[10px] font-extrabold text-primary">{item[0].split(" ").map(value=>value[0]).join("")}</span><div className="min-w-0"><h3 className="truncate text-[11px] font-extrabold">{item[0]}</h3><p className="mt-1 text-[9px] text-slate-400">{item[1]} · {item[2]}</p><div className="mt-2 flex items-center gap-2"><b className="text-xs">{item[3]}</b><span className={`rounded-full px-2 py-1 text-[8px] font-bold ${statusStyle[item[5] as DayStatus]}`}>{item[4]} · {item[5]}</span></div></div></div><div className="mt-4 flex gap-2"><button onClick={()=>setEvent(item)} className="flex h-8 flex-1 items-center justify-center gap-1 rounded-lg border border-slate-200 text-[8px] font-bold"><Eye size={12}/>Детали</button><Link href={`/students/${item[6]}`} className="flex h-8 flex-1 items-center justify-center rounded-lg bg-primary text-[8px] font-bold text-white">Личное дело</Link></div></article>)}</div></section>:null}
  {active==="По группам"?<section className="mt-5 overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-card"><div className="px-5 py-4"><h2 className="text-sm font-extrabold">Посещаемость по группам</h2><p className="mt-1 text-[9px] text-slate-400">Сводка на 22 июня 2026</p></div><div className="overflow-x-auto"><table className="w-full min-w-[1180px]"><thead><tr className="bg-slate-50/80">{["Группа","Куратор","Всего","Пришли","Отсутствуют","Опоздали","Ушли раньше","Посещаемость","Риск","Действия"].map(column=><th key={column} className="px-4 py-3 text-left text-[9px] font-extrabold uppercase tracking-wider text-slate-400">{column}</th>)}</tr></thead><tbody>{groups.map(item=><tr key={item[0]} className="border-t border-slate-100"><td className="px-4 py-4 text-[10px] font-extrabold">{item[0]}</td>{item.slice(1,8).map((cell,index)=><td key={`${cell}-${index}`} className="px-4 py-4 text-[10px] text-slate-500">{cell}</td>)}<td className="px-4"><span className={`rounded-full px-2.5 py-1 text-[9px] font-bold ${item[8]==="Высокий"?"bg-orange-50 text-orange-700":item[8]==="Средний"?"bg-amber-50 text-amber-700":"bg-emerald-50 text-emerald-700"}`}>{item[8]}</span></td><td className="px-4"><button onClick={()=>setGroup(item)} className="rounded-lg bg-primary px-3 py-2 text-[9px] font-bold text-white">Открыть группу</button></td></tr>)}</tbody></table></div></section>:null}
  {active==="По студентам"?<section className="mt-5 overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-card"><div className="flex flex-col justify-between gap-3 border-b border-slate-100 p-4 sm:flex-row"><div><h2 className="text-sm font-extrabold">Персональная посещаемость</h2><p className="mt-1 text-[9px] text-slate-400">Все студенты колледжа</p></div><label className="flex h-9 w-full max-w-xs items-center gap-2 rounded-xl border border-slate-200 px-3"><Search size={14} className="text-slate-400"/><input value={query} onChange={event=>setQuery(event.target.value)} className="min-w-0 flex-1 text-[9px] outline-none" placeholder="Поиск студента…"/></label></div><div className="overflow-x-auto"><table className="w-full min-w-[1370px]"><thead><tr className="bg-slate-50/80">{["Студент","Группа","Статус сегодня","Вход","Терминал входа","Выход","Терминал выхода","За месяц","Опозданий","Пропусков","Действия"].map(column=><th key={column} className="px-4 py-3 text-left text-[9px] font-extrabold uppercase tracking-wider text-slate-400">{column}</th>)}</tr></thead><tbody>{filteredStudents.map(item=><tr key={item[0]} className="border-t border-slate-100"><td className="px-4 py-4 text-[10px] font-bold">{item[0]}</td><td className="px-4 py-4 text-[10px]">{item[1]}</td><td className="px-4"><span className={`rounded-full px-2.5 py-1 text-[9px] font-bold ${statusStyle[item[2] as DayStatus]}`}>{item[2]}</span></td>{item.slice(3,10).map((cell,index)=><td key={`${cell}-${index}`} className="px-4 py-4 text-[10px] text-slate-500">{cell}</td>)}<td className="px-4"><Link href={`/students/${item[10]}`} className="rounded-lg bg-primary px-3 py-2 text-[9px] font-bold text-white">Открыть личное дело</Link></td></tr>)}</tbody></table></div></section>:null}
  {active==="Терминалы"?<section className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{terminals.map(item=><article key={item[0]} className="rounded-2xl border border-slate-100 bg-white p-5 shadow-card"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-primary"><MonitorSmartphone size={20}/></span><span className={`flex items-center gap-1 rounded-full px-2.5 py-1 text-[9px] font-bold ${item[1]==="Онлайн"?"bg-emerald-50 text-emerald-700":"bg-red-50 text-red-700"}`}>{item[1]==="Онлайн"?<Wifi size={11}/>:<WifiOff size={11}/>} {item[1]}</span></div><h3 className="mt-4 text-sm font-extrabold">{item[0]}</h3><dl className="mt-4 space-y-2 text-[9px]"><div className="flex justify-between"><dt className="text-slate-400">Последнее событие</dt><dd className="font-bold">{item[2]}</dd></div><div className="flex justify-between"><dt className="text-slate-400">Событий сегодня</dt><dd className="font-bold">{item[3]}</dd></div><div className="flex justify-between"><dt className="text-slate-400">Корпус</dt><dd className="font-bold">{item[4]}</dd></div><div className="flex justify-between"><dt className="text-slate-400">Зона доступа</dt><dd className="font-bold">{item[5]}</dd></div></dl><button onClick={()=>showToast(`Открыты события терминала «${item[0]}»`)} className="mt-4 h-9 w-full rounded-xl border border-slate-200 text-[9px] font-bold">Показать события</button></article>)}</section>:null}
  {active==="Корректировки"?<section className="mt-5 overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-card"><div className="flex items-center justify-between px-5 py-4"><div><h2 className="text-sm font-extrabold">Ручные корректировки</h2><p className="mt-1 text-[9px] text-slate-400">История изменений и подтверждающие документы</p></div><button onClick={()=>setCorrection(true)} className="h-9 rounded-xl bg-primary px-3 text-[9px] font-bold text-white">Добавить корректировку</button></div><div className="overflow-x-auto"><table className="w-full min-w-[1050px]"><thead><tr className="bg-slate-50/80">{["Номер","Студент","Дата","Изменение","Кто внёс","Причина","Документ","Статус проверки"].map(column=><th key={column} className="px-4 py-3 text-left text-[9px] font-extrabold uppercase tracking-wider text-slate-400">{column}</th>)}</tr></thead><tbody>{corrections.map(row=><tr key={row[0]} className="border-t border-slate-100">{row.map((cell,index)=><td key={`${cell}-${index}`} className="px-4 py-4 text-[10px] text-slate-500">{index===0||index===1?<b className={index===0?"text-primary":"text-slate-800"}>{cell}</b>:index===7?<span className={`rounded-full px-2.5 py-1 text-[9px] font-bold ${cell==="Подтверждено"?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{cell}</span>:cell}</td>)}</tr>)}</tbody></table></div></section>:null}
  {active==="Отчёты"?<section className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{reportDefinitions.map(([title,description,Icon])=><article key={title} className="rounded-2xl border border-slate-100 bg-white p-5 shadow-card"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-primary"><Icon size={19}/></span><h3 className="mt-4 text-sm font-extrabold">{title}</h3><p className="mt-2 min-h-10 text-[9px] leading-4 text-slate-500">{description}</p><div className="mt-4 flex gap-2"><button onClick={()=>showToast(`${title}: PDF подготовлен`)} className="flex h-9 flex-1 items-center justify-center gap-1 rounded-xl bg-red-50 text-[9px] font-bold text-red-700"><FileText size={13}/>PDF</button><button onClick={()=>showToast(`${title}: Excel подготовлен`)} className="flex h-9 flex-1 items-center justify-center gap-1 rounded-xl bg-emerald-50 text-[9px] font-bold text-emerald-700"><FileSpreadsheet size={13}/>Excel</button></div></article>)}</section>:null}
  {group?<GroupModal group={group} onClose={()=>setGroup(null)}/>:null}{event?<DetailModal event={event} onClose={()=>setEvent(null)}/>:null}{correction?<CorrectionModal onClose={()=>setCorrection(false)} onSave={()=>{setCorrection(false);showToast("Ручная корректировка сохранена")}}/>:null}{toast?<div className="fixed bottom-6 right-6 z-[70] flex items-center gap-3 rounded-xl bg-slate-900 px-4 py-3 text-xs font-bold text-white shadow-2xl"><span className="grid h-6 w-6 place-items-center rounded-full bg-emerald-500"><Check size={14}/></span>{toast}</div>:null}</div>}
