"use client";

import { useMemo, useState } from "react";
import { Check, Download, FileText, Filter, GraduationCap, Plus, Search, X } from "lucide-react";
import { useTasks } from "@/components/task-context";

type SectionPageProps = { title: string; description: string; columns: string[]; rows: string[][]; action?: string; studentHistory?: boolean };

function StudentRelatedTasks({student}:{student:string}){
  const {tasks}=useTasks();const related=tasks.filter(task=>`${task.title} ${task.related}`.includes(student.split(" ")[0])).slice(0,3);
  return <aside className="fixed right-6 top-24 z-[60] hidden w-72 rounded-2xl border border-blue-100 bg-white p-4 shadow-2xl xl:block"><h3 className="text-xs font-extrabold">Связанные задачи</h3><p className="mt-1 text-[9px] text-slate-400">Поручения по карточке студента</p><div className="mt-3 space-y-2">{related.length?related.map(task=><div key={task.id} className="rounded-xl bg-slate-50 p-3"><p className="text-[9px] font-bold leading-4 text-slate-700">{task.title}</p><p className="mt-1 text-[8px] text-slate-400">{task.status} · {task.responsible}</p></div>):<p className="rounded-xl bg-slate-50 p-3 text-[9px] text-slate-400">Связанных задач нет</p>}</div></aside>
}

export function SectionPage({ title, description, columns, rows, action = "Добавить запись", studentHistory = false }: SectionPageProps) {
  const [query, setQuery] = useState("");
  const [tab, setTab] = useState("Все");
  const [modal, setModal] = useState(false);
  const [saved, setSaved] = useState(false);
  const [selectedStudent, setSelectedStudent] = useState<string[] | null>(null);
  const visible = useMemo(() => rows.filter((row) => row.join(" ").toLowerCase().includes(query.toLowerCase())), [query, rows]);
  function save(event: React.FormEvent) { event.preventDefault(); setModal(false); setSaved(true); window.setTimeout(() => setSaved(false), 2500); }

  return <div className="mx-auto max-w-[1500px] animate-rise">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="text-2xl font-extrabold tracking-[-.025em] sm:text-[28px]">{title}</h1><p className="mt-1.5 text-sm text-slate-500">{description}</p></div><button onClick={() => setModal(true)} className="flex h-10 items-center justify-center gap-2 rounded-xl bg-primary px-4 text-xs font-bold text-white shadow-lg shadow-blue-100 hover:bg-blue-700"><Plus size={17}/>{action}</button></div>
    <div className="mt-7 overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-card">
      <div className="flex flex-col justify-between gap-4 border-b border-slate-100 p-4 sm:flex-row sm:items-center sm:px-5"><div className="flex rounded-xl bg-slate-50 p-1">{["Все", "Активные", "Архив"].map((item) => <button key={item} onClick={() => setTab(item)} className={`rounded-lg px-4 py-2 text-[11px] font-bold ${tab === item ? "bg-white text-primary shadow-sm" : "text-slate-400"}`}>{item}</button>)}</div><div className="flex gap-2"><label className="flex h-10 flex-1 items-center gap-2 rounded-xl border border-slate-200 px-3 sm:w-64"><Search size={16} className="text-slate-400"/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Поиск…" className="min-w-0 flex-1 text-xs outline-none"/></label><button title="Фильтры" className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 text-slate-500 hover:bg-slate-50"><Filter size={16}/></button><button title="Скачать" className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 text-slate-500 hover:bg-slate-50"><Download size={16}/></button></div></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[760px] border-collapse"><thead><tr className="bg-slate-50/70">{columns.map((column) => <th key={column} className="px-5 py-3.5 text-left text-[10px] font-extrabold uppercase tracking-[.08em] text-slate-400">{column}</th>)}</tr></thead><tbody>{visible.map((row) => <tr key={row.join("-")} onClick={() => studentHistory && setSelectedStudent(row)} className={`border-t border-slate-100 transition hover:bg-blue-50/30 ${studentHistory ? "cursor-pointer" : ""}`}>{row.map((cell, j) => <td key={`${cell}${j}`} className="px-5 py-4 text-xs text-slate-600">{j === 0 ? <div className="flex items-center gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-blue-50 text-[10px] font-extrabold text-primary">{cell.split(" ").map((part) => part[0]).slice(0,2).join("")}</span><span><b className="block text-slate-800">{cell}</b>{studentHistory?<small className="mt-1 block text-[9px] font-bold text-primary">Открыть карточку</small>:null}</span></div> : j === row.length - 1 ? <span className={`inline-flex rounded-full px-2.5 py-1 text-[10px] font-bold ${cell.includes("Актив") || cell.includes("Выполн") || cell.includes("Подписан") || cell.includes("Высок") ? "bg-emerald-50 text-emerald-600" : cell.includes("Ожида") || cell.includes("Средн") ? "bg-amber-50 text-amber-600" : "bg-slate-100 text-slate-500"}`}>{cell}</span> : cell}</td>)}</tr>)}</tbody></table>{visible.length === 0 ? <div className="py-16 text-center"><Search size={28} className="mx-auto text-slate-300"/><p className="mt-3 text-sm font-bold text-slate-600">Ничего не найдено</p><p className="mt-1 text-xs text-slate-400">Попробуйте изменить запрос</p></div> : null}</div>
      <div className="flex items-center justify-between border-t border-slate-100 px-5 py-4 text-[11px] text-slate-400"><span>Показано {visible.length} из {rows.length} записей</span><div className="flex gap-1"><button className="rounded-lg border border-slate-200 px-3 py-1.5">Назад</button><button className="rounded-lg bg-primary px-3 py-1.5 font-bold text-white">1</button><button className="rounded-lg border border-slate-200 px-3 py-1.5">Далее</button></div></div>
    </div>
    {saved ? <div className="fixed bottom-6 right-6 flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-3 text-xs font-bold text-white shadow-xl"><Check size={17} className="text-emerald-400"/>Изменения сохранены</div> : null}
    {modal ? <div className="fixed inset-0 z-50 grid place-items-center bg-slate-900/30 p-4"><form onSubmit={save} className="w-full max-w-md animate-rise rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><h2 className="text-lg font-extrabold">{action}</h2><p className="mt-1 text-xs text-slate-400">Заполните данные для демо-записи</p></div><button type="button" onClick={() => setModal(false)} className="grid h-9 w-9 place-items-center rounded-lg bg-slate-50 text-slate-500"><X size={18}/></button></div><div className="mt-6 space-y-4"><label className="block text-xs font-bold text-slate-600">Название<input required className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-xs outline-none focus:border-primary" placeholder="Введите название"/></label><label className="block text-xs font-bold text-slate-600">Категория<select className="mt-2 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-xs outline-none"><option>Основная</option><option>Дополнительная</option></select></label><label className="block text-xs font-bold text-slate-600">Комментарий<textarea className="mt-2 min-h-24 w-full resize-none rounded-xl border border-slate-200 p-3 text-xs outline-none focus:border-primary" placeholder="Краткое описание"/></label></div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={() => setModal(false)} className="h-10 rounded-xl border border-slate-200 px-4 text-xs font-bold text-slate-500">Отмена</button><button className="h-10 rounded-xl bg-primary px-5 text-xs font-bold text-white">Сохранить</button></div></form></div> : null}
    {selectedStudent ? <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-slate-900/35 p-4 backdrop-blur-[2px]" onMouseDown={(event) => { if (event.target === event.currentTarget) setSelectedStudent(null); }}><div className="my-4 w-full max-w-3xl animate-rise rounded-[22px] bg-white shadow-2xl"><div className="flex items-start justify-between border-b border-slate-100 px-6 py-5"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-primary"><GraduationCap size={20}/></span><div><h2 className="text-lg font-extrabold">Карточка студента</h2><p className="mt-1 text-xs text-slate-400">{selectedStudent[0]} · {selectedStudent[1]}</p></div></div><button onClick={() => setSelectedStudent(null)} className="grid h-9 w-9 place-items-center rounded-xl bg-slate-50 text-slate-400"><X size={18}/></button></div><div className="p-6"><section className="rounded-2xl border border-slate-100 p-5"><div className="flex items-center justify-between"><div><h3 className="text-sm font-extrabold">История поступления и движения</h3><p className="mt-1 text-[10px] text-slate-400">Полный путь студента в колледже</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-[9px] font-bold text-emerald-700">Личное дело активно</span></div><div className="mt-5 space-y-0">{[["18.08.2024","Заявка на поступление","ЗП-2024-0441"],["28.08.2024","Приказ о зачислении","Приказ №184"],["01.09.2024","Зачислен в группу",selectedStudent[1]],["15.01.2025","Перевод между группами","ИС-23-2 → ИС-23-1"],["—","Академический отпуск","Записей нет"],["—","Восстановление","Записей нет"],["Июнь 2027","Выпуск / отчисление","Ожидается выпуск"],["После выпуска","Архивный статус","Будет передано в архив"]].map(([date,title,detail],index,array)=><div key={title} className="relative flex gap-4 pb-5 last:pb-0"><span className={`relative z-10 mt-0.5 grid h-7 w-7 shrink-0 place-items-center rounded-full ${index<4?"bg-blue-50 text-primary":"bg-slate-100 text-slate-400"}`}>{index<4?<Check size={13}/>:<FileText size={13}/>}</span>{index<array.length-1?<span className="absolute bottom-0 left-[13px] top-7 w-px bg-slate-200"/>:null}<div><p className="text-[10px] font-bold text-slate-400">{date}</p><p className="mt-1 text-xs font-extrabold text-slate-700">{title}</p><p className="mt-1 text-[10px] text-slate-500">{detail}</p></div></div>)}</div></section></div></div></div> : null}{selectedStudent?<StudentRelatedTasks student={selectedStudent[0]}/>:null}
  </div>;
}
