"use client";

import { createContext, useContext, useState } from "react";

export type TaskStatus = "Новая" | "В работе" | "Ожидает проверки" | "Выполнена" | "Просрочена" | "Архив";
export type TaskPriority = "Низкий" | "Средний" | "Высокий" | "Критический";
export type TaskType = "Студент" | "Документ" | "AI" | "Посещаемость" | "Дисциплина" | "Кадры" | "Приёмная комиссия";
export type TaskItem = { id:number; number:string; title:string; description:string; type:TaskType; priority:TaskPriority; status:TaskStatus; author:string; responsible:string; related:string; deadline:string; created:string; observers:string[]; history:string[]; checklist:string[]; comments:string[] };

const initialTasks:TaskItem[] = [
  {id:1,number:"ЗД-2026-0148",title:"Провести беседу со студентом из зоны риска",description:"Провести индивидуальную беседу с Айданой Сериковой по AI-сигналу снижения успеваемости.",type:"AI",priority:"Критический",status:"Новая",author:"Айгуль Садыкова",responsible:"Психолог",related:"Айдана Серикова · ИС-23-1",deadline:"22.06.2026",created:"20.06.2026",observers:["Куратор ИС-23-1","Завуч"],history:["Задача создана директором","Назначена психологу"],checklist:["Изучить AI-рекомендацию","Провести беседу","Добавить итоговый комментарий"],comments:["Просьба обратить внимание на динамику за последние две недели."]},
  {id:2,number:"ЗД-2026-0147",title:"Связаться с родителем студента",description:"Уточнить причины систематических пропусков занятий.",type:"Студент",priority:"Высокий",status:"В работе",author:"Завуч",responsible:"Куратор",related:"Алимжан Нурланов · ИС-23-1",deadline:"22.06.2026",created:"20.06.2026",observers:["Психолог"],history:["Задача создана","Куратор взял задачу в работу"],checklist:["Позвонить родителю","Зафиксировать результат"],comments:[]},
  {id:3,number:"ЗД-2026-0142",title:"Проверить академическую задолженность",description:"Проверить ведомости и сформировать список студентов с задолженностями.",type:"Дисциплина",priority:"Высокий",status:"Просрочена",author:"Директор",responsible:"Завуч",related:"Группа ЭЛ-22-1",deadline:"20.06.2026",created:"17.06.2026",observers:["Директор"],history:["Задача создана","Срок исполнения истёк"],checklist:["Проверить ведомости","Сформировать список","Назначить пересдачи"],comments:[]},
  {id:4,number:"ЗД-2026-0139",title:"Зарегистрировать входящее письмо",description:"Зарегистрировать письмо Управления образования и назначить исполнителя.",type:"Документ",priority:"Высокий",status:"Новая",author:"Директор",responsible:"Канцелярия",related:"ВХ-2026-0418",deadline:"22.06.2026",created:"22.06.2026",observers:["Завуч"],history:["Создано из карточки документа"],checklist:["Присвоить номер","Загрузить скан","Назначить ответственного"],comments:[]},
  {id:5,number:"ЗД-2026-0136",title:"Согласовать приказ о зачислении",description:"Проверить проект приказа и согласовать список зачисленных студентов.",type:"Документ",priority:"Критический",status:"Ожидает проверки",author:"Канцелярия",responsible:"Директор",related:"Приказ №142",deadline:"23.06.2026",created:"19.06.2026",observers:["Завуч","Приёмная комиссия"],history:["Задача создана","Проект приказа подготовлен","Отправлено на проверку"],checklist:["Проверить список","Проверить основание","Согласовать"],comments:["Список проверен приёмной комиссией."]},
  {id:6,number:"ЗД-2026-0131",title:"Закрыть оценки по базам данных",description:"Выставить итоговые оценки и закрыть электронную ведомость.",type:"Дисциплина",priority:"Средний",status:"В работе",author:"Завуч",responsible:"Преподаватель",related:"ИС-23-1 · Базы данных",deadline:"25.06.2026",created:"18.06.2026",observers:["Завуч"],history:["Задача назначена преподавателю","Взята в работу"],checklist:["Выставить оценки","Проверить пропуски","Закрыть ведомость"],comments:[]},
  {id:7,number:"ЗД-2026-0128",title:"Проверить срок трудового договора",description:"Проверить условия продления договора преподавателя.",type:"Кадры",priority:"Средний",status:"Новая",author:"Директор",responsible:"Кадровик",related:"Г. Касенова · Договор ТД-118",deadline:"26.06.2026",created:"18.06.2026",observers:["Директор"],history:["Задача создана из кадрового реестра"],checklist:["Проверить срок","Подготовить допсоглашение"],comments:[]},
  {id:8,number:"ЗД-2026-0124",title:"Исполнить письмо Управления образования",description:"Подготовить сведения о контингенте и проект исходящего ответа.",type:"Документ",priority:"Высокий",status:"В работе",author:"Канцелярия",responsible:"М. Соколова",related:"ВХ-2026-0418",deadline:"25.06.2026",created:"17.06.2026",observers:["Директор","Канцелярия"],history:["Назначен ответственный","Задача взята в работу"],checklist:["Собрать данные","Подготовить письмо","Передать на подпись"],comments:[]},
  {id:9,number:"ЗД-2026-0119",title:"Проверить документы кандидата",description:"Провести комплектность и верификацию документов кандидата.",type:"Приёмная комиссия",priority:"Средний",status:"Ожидает проверки",author:"Завуч",responsible:"Приёмная комиссия",related:"ЗП-2026-0183 · Мадина Сейтова",deadline:"24.06.2026",created:"16.06.2026",observers:["Завуч"],history:["Создано из заявки кандидата","Документы загружены"],checklist:["Проверить ИИН","Проверить аттестат","Проверить медсправку"],comments:[]},
  {id:10,number:"ЗД-2026-0114",title:"Проверить Face ID терминал",description:"Диагностировать офлайн-терминал на служебном входе.",type:"Посещаемость",priority:"Высокий",status:"Выполнена",author:"Директор",responsible:"IT-специалист",related:"EDUS Staff 01",deadline:"19.06.2026",created:"18.06.2026",observers:["Охрана"],history:["Задача создана","Терминал проверен","Работа выполнена"],checklist:["Проверить питание","Проверить сеть","Перезапустить терминал"],comments:["Причина — отключение питания. Терминал восстановлен."]},
];

type CreateTaskInput = Partial<TaskItem> & Pick<TaskItem,"title"|"type"|"responsible"|"related">;
type TaskContextValue = { tasks:TaskItem[]; createTask:(input:CreateTaskInput)=>TaskItem; updateTask:(id:number,patch:Partial<TaskItem>,historyLabel?:string)=>void; addComment:(id:number,comment:string)=>void };
const TaskContext=createContext<TaskContextValue|null>(null);

export function TaskProvider({children}:{children:React.ReactNode}){
  const [tasks,setTasks]=useState(initialTasks);
  function createTask(input:CreateTaskInput){const task:TaskItem={id:Date.now(),number:`ЗД-2026-${String(tasks.length+149).padStart(4,"0")}`,title:input.title,type:input.type,responsible:input.responsible,related:input.related,description:input.description??"Новая задача EDUS",priority:input.priority??"Средний",status:input.status??"Новая",author:input.author??"Айгуль Садыкова",deadline:input.deadline??"30.06.2026",created:"22.06.2026",observers:input.observers??[],history:input.history??["Задача создана"],checklist:input.checklist??["Принять задачу в работу","Выполнить поручение"],comments:input.comments??[]};setTasks(current=>[task,...current]);return task}
  function updateTask(id:number,patch:Partial<TaskItem>,historyLabel?:string){setTasks(current=>current.map(task=>task.id===id?{...task,...patch,history:historyLabel?[...task.history,historyLabel]:task.history}:task))}
  function addComment(id:number,comment:string){setTasks(current=>current.map(task=>task.id===id?{...task,comments:[...task.comments,comment],history:[...task.history,"Добавлен комментарий"]}:task))}
  return <TaskContext.Provider value={{tasks,createTask,updateTask,addComment}}>{children}</TaskContext.Provider>
}
export function useTasks(){const context=useContext(TaskContext);if(!context)throw new Error("useTasks должен использоваться внутри TaskProvider");return context}
