"use client";

import { useState } from "react";
import { Bell, Building2, Check, LockKeyhole, Palette, Save, UserRound } from "lucide-react";

const sections = [["Профиль", UserRound],["Колледж", Building2],["Уведомления", Bell],["Безопасность", LockKeyhole],["Интерфейс", Palette]] as const;

export default function SettingsPage(){
  const [active,setActive]=useState("Профиль"); const [saved,setSaved]=useState(false);
  function save(){setSaved(true);window.setTimeout(()=>setSaved(false),2200)}
  return <div className="mx-auto max-w-[1200px] animate-rise"><div><h1 className="text-2xl font-extrabold tracking-[-.025em] sm:text-[28px]">Настройки</h1><p className="mt-1.5 text-sm text-slate-500">Параметры профиля и портала колледжа</p></div><div className="mt-7 grid gap-5 lg:grid-cols-[230px_1fr]"><aside className="h-fit rounded-2xl border border-slate-100 bg-white p-2 shadow-card">{sections.map(([label,Icon])=><button key={label} onClick={()=>setActive(label)} className={`flex h-11 w-full items-center gap-3 rounded-xl px-3 text-xs font-bold ${active===label?"bg-blue-50 text-primary":"text-slate-500 hover:bg-slate-50"}`}><Icon size={17}/>{label}</button>)}</aside><section className="rounded-2xl border border-slate-100 bg-white p-5 shadow-card sm:p-7"><h2 className="text-base font-extrabold">{active}</h2><p className="mt-1 text-xs text-slate-400">Настройте данные раздела и сохраните изменения</p><div className="mt-7 grid gap-5 sm:grid-cols-2"><label className="text-xs font-bold text-slate-600">Имя<input defaultValue="Айгуль" className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-xs outline-none focus:border-primary"/></label><label className="text-xs font-bold text-slate-600">Фамилия<input defaultValue="Садыкова" className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-xs outline-none focus:border-primary"/></label><label className="text-xs font-bold text-slate-600">Электронная почта<input defaultValue="director@edus.kz" className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-xs outline-none focus:border-primary"/></label><label className="text-xs font-bold text-slate-600">Телефон<input defaultValue="+7 (701) 555-42-18" className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-xs outline-none focus:border-primary"/></label><label className="text-xs font-bold text-slate-600 sm:col-span-2">Название организации<input defaultValue="Высший колледж информационных технологий" className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-xs outline-none focus:border-primary"/></label></div><div className="mt-7 border-t border-slate-100 pt-5"><button onClick={save} className="flex h-10 items-center gap-2 rounded-xl bg-primary px-5 text-xs font-bold text-white"><Save size={16}/>Сохранить изменения</button></div></section></div>{saved?<div className="fixed bottom-6 right-6 flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-3 text-xs font-bold text-white shadow-xl"><Check size={17} className="text-emerald-400"/>Настройки сохранены</div>:null}</div>
}
